set_instrument_and_final_stage_var(LLVM_TARGETS_TO_BUILD "Native" STRING)

set(COMPILER_RT_USE_BUILTINS_LIBRARY OFF CACHE BOOL "")
set_instrument_and_final_stage_var(COMPILER_RT_USE_BUILTINS_LIBRARY "OFF" BOOL)
set(COMPILER_RT_BUILD_BUILTINS OFF CACHE BOOL "")
set_instrument_and_final_stage_var(COMPILER_RT_BUILD_BUILTINS "OFF" BOOL)
set(LIBCXX_USE_COMPILER_RT OFF CACHE BOOL "")
set_instrument_and_final_stage_var(LIBCXX_USE_COMPILER_RT "OFF" BOOL)
set(LIBCXXABI_USE_COMPILER_RT OFF CACHE BOOL "")
set_instrument_and_final_stage_var(LIBCXXABI_USE_COMPILER_RT "OFF" BOOL)
set(LIBCXXABI_USE_LLVM_UNWINDER OFF CACHE BOOL "")
set_instrument_and_final_stage_var(LIBCXXABI_USE_LLVM_UNWINDER "OFF" BOOL)
set(LLVM_BUILD_DOCS OFF CACHE BOOL "")
set_instrument_and_final_stage_var(LLVM_BUILD_DOCS "OFF" BOOL)
set(LLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN ON CACHE BOOL "")
set_instrument_and_final_stage_var(LLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN "ON" BOOL)
set(LLVM_ENABLE_CURL OFF CACHE BOOL "")
set_instrument_and_final_stage_var(LLVM_ENABLE_CURL "OFF" BOOL)

set_instrument_and_final_stage_var(PACKAGE_VENDOR "LoZ Open Source Ecosystem (https://www.ibm.com/community/z/usergroups/opensource)" STRING)

if(LLVM_RELEASE_CLANG_SYSTEMZ_DEFAULT_ARCH)
  set(CLANG_SYSTEMZ_DEFAULT_ARCH "${LLVM_RELEASE_CLANG_SYSTEMZ_DEFAULT_ARCH}" CACHE STRING "")
  set_instrument_and_final_stage_var(CLANG_SYSTEMZ_DEFAULT_ARCH "${LLVM_RELEASE_CLANG_SYSTEMZ_DEFAULT_ARCH}" STRING)
endif()
