# © Copyright IBM Corporation 2017, 2022.
# LICENSE: Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)

#################### Dockerfile for Auditbeat 8.4.3 #############################
# Beats is the platform for single-purpose data shippers
#
# To build this image, from the directory containing this Dockerfile
# (assuming that the file is named Dockerfile):
# docker build -t <image_name> .
#
# To run, see "Run Auditbeat on Docker" guide available at https://www.elastic.co/guide/en/beats/auditbeat/current/running-on-docker.html
#################################################################################

# Base image
FROM s390x/ubuntu:20.04 AS builder

# The author
LABEL maintainer="LoZ Open Source Ecosystem (https://www.ibm.com/community/z/usergroups/opensource)"

ARG BEATS_VER=8.4.3

# Set environment variable
ENV BEATNAME=auditbeat
ENV BEATHOME=/usr/share/$BEATNAME
ENV SOURCE_DIR=/tmp/source
WORKDIR $SOURCE_DIR
ENV GOPATH=$SOURCE_DIR
ENV PATH=$PATH:/usr/local/go/bin/:$GOPATH/bin:/usr/local/bin
ENV GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=true
ENV PYTHON_EXE=python3
ENV PYTHON_ENV=/tmp/venv3
ENV TZ=America/Toronto

# Install dependencies
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    git \
    curl \
    make \
    wget \
    tar \
    gcc \
    g++ \
    libcap-dev \
    libpcap0.8-dev \
    openssl \
    libssh-dev \
    acl \
    rsync \
    patch \
    fdclone \
    libffi-dev \
    libsystemd-dev \
    libjpeg-dev \
    libpython3-dev \
    python3.9 \
    python3.9-dev \
    python3.9-venv \
    python3-lib2to3 \
    python3.9-distutils \
    python3-testresources \
# Install go and download beats source code
 && /usr/bin/update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 10 \
 && /usr/bin/update-alternatives --set python3 /usr/bin/python3.9 \
 && /usr/bin/update-alternatives --display python3 \
 && python3 -V \
 && wget https://bootstrap.pypa.io/get-pip.py \
 && python3 get-pip.py \
 && rm get-pip.py \
 && cd $SOURCE_DIR \
 && wget -O rustup-init.sh https://sh.rustup.rs \
 && bash rustup-init.sh -y \
 && export PATH=$PATH:$HOME/.cargo/bin \
 && rustup toolchain install 1.59.0 \
 &&	rustup default 1.59.0 \
 && wget https://go.dev/dl/go1.17.12.linux-s390x.tar.gz \
 && chmod ugo+r go1.17.12.linux-s390x.tar.gz \
 && tar -C /usr/local -xzf go1.17.12.linux-s390x.tar.gz \
 && setfacl -dm u::rwx,g::r,o::r $GOPATH \
 && mkdir -p $GOPATH/src/github.com/elastic  \
 && cd $GOPATH/src/github.com/elastic  \
 && git clone https://github.com/elastic/beats.git  \
 && cd beats  \
 && git checkout v${BEATS_VER}  \
# Building auditbeat
 && cd $GOPATH/src/github.com/elastic/beats/${BEATNAME} \
 && make \
 && make update \
 && make fmt

# Setup directory layout
RUN mkdir -p $BEATHOME \
 && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/${BEATNAME} $BEATHOME \
 && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/${BEATNAME}.yml $BEATHOME \
 && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/${BEATNAME}.reference.yml $BEATHOME \
 && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/build/fields/fields.all.yml $BEATHOME/fields.yml \
 && mkdir -p $BEATHOME/audit.rules.d \
 && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/module/auditd/_meta/audit.rules.d/sample-rules-linux-64bit.conf $BEATHOME/audit.rules.d/sample-rules.conf.disabled \
 && cp -r $GOPATH/src/github.com/elastic/beats/${BEATNAME}/build/kibana $BEATHOME \
 && mkdir -p $BEATHOME/data $BEATHOME/logs \
 && chown -R root:root $BEATHOME \
 && find $BEATHOME -type d -exec chmod 0755 {} \; \
 && find $BEATHOME -type f -exec chmod 0644 {} \; \
 && chmod 0775 $BEATHOME/data $BEATHOME/logs \
 && chmod 0755 $BEATHOME/$BEATNAME

FROM s390x/ubuntu:20.04

LABEL maintainer="LoZ Open Source Ecosystem (https://www.ibm.com/community/z/usergroups/opensource)"

ENV ELASTIC_CONTAINER "true"
ENV BEATNAME=auditbeat
ENV BEATHOME=/usr/share/$BEATNAME
ENV PATH=$BEATHOME:$PATH

RUN apt-get update && apt-get install -y libpcap0.8 curl sudo \
 && curl --retry 8 -S -L -O "https://github.com/krallin/tini/releases/download/v0.19.0/tini-s390x" \
 && mv tini-s390x /usr/bin/tini \
 && chmod +x /usr/bin/tini

COPY docker-entrypoint /usr/local/bin/docker-entrypoint
RUN chmod 755 /usr/local/bin/docker-entrypoint

COPY --from=builder /usr/share/$BEATNAME /usr/share/$BEATNAME

RUN groupadd --gid 1000 $BEATNAME \
 && useradd -M --uid 1000 --gid 1000 --groups 0 --home /usr/share/$BEATHOME $BEATNAME \
 && passwd -d $BEATNAME

#USER $BEATNAME

ENV LIBBEAT_MONITORING_CGROUPS_HIERARCHY_OVERRIDE=/

WORKDIR $BEATHOME
ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/docker-entrypoint"]
CMD ["-environment", "container"]

#End of Dockerfile
