# © Copyright IBM Corporation 2017, 2024.
# LICENSE: Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)

#################### Dockerfile for Auditbeat 8.15.2 #############################
# Beats is the platform for single-purpose data shippers
#
# To build this image, from the directory containing this Dockerfile
# (assuming that the file is named Dockerfile):
# docker build -t <image_name> .
#
# To run, see "Run Auditbeat on Docker" guide available at https://www.elastic.co/guide/en/beats/auditbeat/current/running-on-docker.html
#################################################################################

# Base image
FROM ubuntu:22.04 AS builder

# The author
LABEL maintainer="LoZ Open Source Ecosystem (https://www.ibm.com/community/z/usergroups/opensource)"

ARG BEATS_VER=8.15.2

# Set environment variable
ENV BEATNAME=auditbeat
ENV BEATHOME=/usr/share/$BEATNAME
ENV SOURCE_DIR=/tmp/source
WORKDIR $SOURCE_DIR
ENV GOPATH=$SOURCE_DIR
ENV PATH=$PATH:/usr/local/go/bin/:$GOPATH/bin:/usr/local/bin
ENV GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=true
ENV PYTHON_EXE=python3
ENV PYTHON_ENV=/tmp/venv3
ENV PATCH_URL="https://raw.githubusercontent.com/linux-on-ibm-z/scripts/master/Beats/${BEATS_VER}/patch"
ENV TZ=America/Toronto

# Install dependencies
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    git \
    curl \
    make \
    wget \
    tar \
    gcc \
    g++ \
    libcap-dev \
    libpcap0.8-dev \
    openssl \
    libssh-dev \
    acl \
    rsync \
    patch \
    fdclone \
    libffi-dev \
    libsystemd-dev \
    libjpeg-dev \
    libbz2-dev \
    libdb-dev \
    libgdbm-dev \
    liblzma-dev \
    libncurses-dev \
    libreadline-dev \
    libsqlite3-dev \
    libssl-dev \
    tk-dev \
    uuid-dev \
    xz-utils \
    zlib1g-dev \
# Install Python 3.11.4
 && cd $SOURCE_DIR \
 && wget https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tgz \
 && tar -xzf Python-3.11.4.tgz \
 && cd Python-3.11.4 \
 && ./configure --prefix=/usr/local --exec-prefix=/usr/local \
 && make \
 && make install \
 && /usr/bin/update-alternatives --install /usr/bin/python python /usr/local/bin/python3.11 10 \
 && /usr/bin/update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.11 10 \
 && /usr/bin/update-alternatives --display python3 \
 && python3 -V \
 && cd $SOURCE_DIR \
 && wget https://bootstrap.pypa.io/get-pip.py \
 && python3 get-pip.py \
 && pip3 install wheel -v \
 && pip3 install "cython<3.0.0" pyyaml==5.4.1 --no-build-isolation -v \
 && rm get-pip.py \
 && rm -rf Python* \
 && wget -O rustup-init.sh https://sh.rustup.rs \
 && bash rustup-init.sh -y \
 && export PATH=$PATH:$HOME/.cargo/bin \
 && rustup toolchain install 1.76.0 \
 && rustup default 1.76.0 \
# Install go and download beats source code
 && wget https://go.dev/dl/go1.22.0.linux-s390x.tar.gz \
 && chmod ugo+r go1.22.0.linux-s390x.tar.gz \
 && tar -C /usr/local -xzf go1.22.0.linux-s390x.tar.gz \
 && setfacl -dm u::rwx,g::r,o::r $GOPATH \
 && mkdir -p $GOPATH/src/github.com/elastic  \
 && cd $GOPATH/src/github.com/elastic  \
 && git clone -b v0.6.0 https://github.com/elastic/ebpfevents.git \
 && cd ebpfevents \
 && curl -sSL ${PATCH_URL}/ebpfevents.patch | git apply - \
 && go install golang.org/x/tools/cmd/stringer@latest \
 && export PATH=$PATH:$(go env GOPATH)/bin \
 && go generate ./... \
 && cd $GOPATH/src/github.com/elastic  \
 && git clone -b v${BEATS_VER} https://github.com/elastic/beats.git  \
 && cd beats  \
# Building auditbeat
 && cd $GOPATH/src/github.com/elastic/beats/${BEATNAME} \
 && go mod edit -replace=github.com/elastic/ebpfevents@v0.6.0=$GOPATH/src/github.com/elastic/ebpfevents \
 && go mod tidy \
 && make \
 && make update \
 && make fmt

# Setup directory layout
RUN mkdir -p $BEATHOME \
 && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/${BEATNAME} $BEATHOME \
 && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/${BEATNAME}.yml $BEATHOME \
 && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/${BEATNAME}.reference.yml $BEATHOME \
 && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/build/fields/fields.all.yml $BEATHOME/fields.yml \
 && mkdir -p $BEATHOME/audit.rules.d \
 && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/module/auditd/_meta/audit.rules.d/sample-rules-linux-64bit.conf $BEATHOME/audit.rules.d/sample-rules.conf.disabled \
 && cp -r $GOPATH/src/github.com/elastic/beats/${BEATNAME}/build/kibana $BEATHOME \
 && mkdir -p $BEATHOME/data $BEATHOME/logs \
 && chown -R root:root $BEATHOME \
 && find $BEATHOME -type d -exec chmod 0755 {} \; \
 && find $BEATHOME -type f -exec chmod 0644 {} \; \
 && chmod 0775 $BEATHOME/data $BEATHOME/logs \
 && chmod 0755 $BEATHOME/$BEATNAME

FROM ubuntu:22.04

LABEL maintainer="LoZ Open Source Ecosystem (https://www.ibm.com/community/z/usergroups/opensource)"

ENV ELASTIC_CONTAINER "true"
ENV BEATNAME=auditbeat
ENV BEATHOME=/usr/share/$BEATNAME
ENV PATH=$BEATHOME:$PATH

RUN for iter in {1..10}; do \
        apt-get update -y && \
        DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --yes ca-certificates curl gawk libpcap0.8 libcap2-bin xz-utils && \
        apt-get clean all && \
        exit_code=0 && break || exit_code=$? && echo "apt-get error: retry $iter in 10s" && sleep 10; \
    done; \
    (exit $exit_code)

RUN curl --retry 8 -S -L -O "https://github.com/krallin/tini/releases/download/v0.19.0/tini-s390x" \
 && mv tini-s390x /usr/bin/tini \
 && chmod +x /usr/bin/tini

COPY docker-entrypoint /usr/local/bin/docker-entrypoint
RUN chmod 755 /usr/local/bin/docker-entrypoint

COPY --from=builder /usr/share/$BEATNAME /usr/share/$BEATNAME

RUN groupadd --gid 1000 $BEATNAME \
 && useradd -M --uid 1000 --gid 1000 --groups 0 --home /usr/share/$BEATHOME $BEATNAME \
 && passwd -d $BEATNAME

USER 1000

ENV LIBBEAT_MONITORING_CGROUPS_HIERARCHY_OVERRIDE=/

WORKDIR $BEATHOME
ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/docker-entrypoint"]
CMD ["-environment", "container"]

#End of Dockerfile
