# © Copyright IBM Corporation 2017, 2023.
# LICENSE: Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)

#################### Dockerfile for Heartbeat 8.11.1 #############################
# Beats is the platform for single-purpose data shippers
#
# To build this image, from the directory containing this Dockerfile
# (assuming that the file is named Dockerfile):
# docker build -t <image_name> .
#
# To run, see "Run Heartbeat on Docker" guide available at https://www.elastic.co/guide/en/beats/heartbeat/current/running-on-docker.html
#################################################################################

# Base image
FROM ubuntu:20.04 AS builder

# The author
LABEL maintainer="LoZ Open Source Ecosystem (https://www.ibm.com/community/z/usergroups/opensource)"

ARG BEATS_VER=8.11.1

# Set environment variable
ENV BEATNAME=heartbeat
ENV BEATHOME=/usr/share/$BEATNAME
ENV SOURCE_DIR=/tmp/source
WORKDIR $SOURCE_DIR
ENV GOPATH=$SOURCE_DIR
ENV PATH=$PATH:/usr/local/go/bin/:$GOPATH/bin:/usr/local/bin
ENV GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=true
ENV PYTHON_EXE=python3
ENV PYTHON_ENV=/tmp/venv3
ENV TZ=America/Toronto

# Install dependencies
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    git \
    curl \
    make \
    wget \
    tar \
    gcc \
    g++ \
    libcap-dev \
    libpcap0.8-dev \
    openssl \
    libssh-dev \
    acl \
    rsync \
    patch \
    fdclone \
    libffi-dev \
    libsystemd-dev \
    libjpeg-dev \
    libbz2-dev \
    libdb-dev \
    libgdbm-dev \
    liblzma-dev \
    libncurses-dev \
    libreadline-dev \
    libsqlite3-dev \
    libssl-dev \
    tk-dev \
    uuid-dev \
    xz-utils \
    zlib1g-dev \
# Install Python 3.11.4
 && cd $SOURCE_DIR \
 && wget https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tgz \
 && tar -xzf Python-3.11.4.tgz \
 && cd Python-3.11.4 \
 && ./configure --prefix=/usr/local --exec-prefix=/usr/local \
 && make \
 && make install \
 && /usr/bin/update-alternatives --install /usr/bin/python python /usr/local/bin/python3.11 10 \
 && /usr/bin/update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.11 10 \
 && /usr/bin/update-alternatives --display python3 \
 && python3 -V \
 && cd $SOURCE_DIR \
 && wget https://bootstrap.pypa.io/get-pip.py \
 && python3 get-pip.py \
 && pip3 install wheel -v \
 && pip3 install "cython<3.0.0" pyyaml==5.4.1 --no-build-isolation -v \
 && rm get-pip.py \
 && cd $SOURCE_DIR \
 && wget -O rustup-init.sh https://sh.rustup.rs \
 && bash rustup-init.sh -y \
 && export PATH=$PATH:$HOME/.cargo/bin \
 && rustup toolchain install 1.65.0 \
 && rustup default 1.65.0 \
 && wget https://go.dev/dl/go1.20.10.linux-s390x.tar.gz \
 && chmod ugo+r go1.20.10.linux-s390x.tar.gz \
 && tar -C /usr/local -xzf go1.20.10.linux-s390x.tar.gz \
 && setfacl -dm u::rwx,g::r,o::r $GOPATH \
 && mkdir -p $GOPATH/src/github.com/elastic  \
 && cd $GOPATH/src/github.com/elastic  \
 && git clone https://github.com/elastic/beats.git  \
 && cd beats  \
 && git checkout v${BEATS_VER}  \
# Building heartbeat
 && cd $GOPATH/src/github.com/elastic/beats/${BEATNAME} \
 && make \
 && make update \
 && make fmt

# Setup directory layout
RUN mkdir -p $BEATHOME \
 && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/${BEATNAME} $BEATHOME \
 && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/${BEATNAME}.yml $BEATHOME \
 && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/${BEATNAME}.reference.yml $BEATHOME \
 && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/fields.yml $BEATHOME/fields.yml \
 && cp -r $GOPATH/src/github.com/elastic/beats/${BEATNAME}/monitors.d $BEATHOME \
 && mkdir -p $BEATHOME/data $BEATHOME/logs \
 && chown -R root:root $BEATHOME \
 && find $BEATHOME -type d -exec chmod 0755 {} \; \
 && find $BEATHOME -type f -exec chmod 0644 {} \; \
 && chmod 0775 $BEATHOME/data $BEATHOME/logs \
 && chmod 0755 $BEATHOME/$BEATNAME

FROM ubuntu:20.04

LABEL maintainer="LoZ Open Source Ecosystem (https://www.ibm.com/community/z/usergroups/opensource)"

ENV ELASTIC_CONTAINER "true"
ENV BEATNAME=heartbeat
ENV BEATHOME=/usr/share/$BEATNAME
ENV NODE_PATH=$BEATHOME/.node
ENV PATH=$BEATHOME:$PATH

RUN for iter in {1..10}; do \
        apt-get update -y && \
        DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --yes ca-certificates curl gawk libpcap0.8 libcap2-bin xz-utils && \
        apt-get clean all && \
        exit_code=0 && break || exit_code=$? && echo "apt-get error: retry $iter in 10s" && sleep 10; \
    done; \
    (exit $exit_code)

RUN apt-get update -y && \
    for iter in {1..10}; do \
        DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --yes \
        libglib2.0-0\
        libnss3\
        libnspr4\
        libatk1.0-0\
        libatk-bridge2.0-0\
        libcups2\
        libdrm2\
        libdbus-1-3\
        libxcb1\
        libxkbcommon0\
        libx11-6\
        libxcomposite1\
        libxdamage1\
        libxext6\
        libxfixes3\
        libxrandr2\
        libgbm1\
        libpango-1.0-0\
        libcairo2\
        libasound2\
        libatspi2.0-0\
        libxshmfence1 \
        fonts-noto \
        fonts-noto-cjk && \
        apt-get clean all && \
        exit_code=0 && break || exit_code=$? && echo "apt-get error: retry $iter in 10s" && sleep 10; \
    done; \
    (exit $exit_code)

RUN echo \
    $NODE_PATH \
    $BEATHOME/.config \
    $BEATHOME/.synthetics \
    $BEATHOME/.npm \
    $BEATHOME/.cache \
    | xargs -IDIR sh -c 'mkdir -p DIR && chmod 0770 DIR'

RUN apt-get update && apt-get install -y libpcap0.8 curl sudo \
 && curl --retry 8 -S -L -O "https://github.com/krallin/tini/releases/download/v0.19.0/tini-s390x" \
 && mv tini-s390x /usr/bin/tini \
 && chmod +x /usr/bin/tini

COPY docker-entrypoint /usr/local/bin/docker-entrypoint
RUN chmod 755 /usr/local/bin/docker-entrypoint

# Setup synthetics env vars
ENV ELASTIC_SYNTHETICS_CAPABLE=true
ENV SUITES_DIR=$BEATHOME/suites
ENV NODE_VERSION=18.16.0
ENV PATH="$NODE_PATH/node/bin:$PATH"

RUN groupadd --gid 1000 $BEATNAME \
 && useradd -M --uid 1000 --gid 1000 --groups 0 --home $BEATHOME $BEATNAME \
 && passwd -d $BEATNAME

# Install the latest version of @elastic/synthetics forcefully ignoring the previously
# cached node_modules, heartbeat then calls the global executable to run test suites
# Setup node

RUN cd /usr/share/heartbeat/.node \
  && NODE_DOWNLOAD_URL="https://nodejs.org/download/release/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-s390x.tar.xz" \
  && mkdir -p node \
  && curl ${NODE_DOWNLOAD_URL} | tar -xJ --strip 1 -C node \
  && chmod ug+rwX -R $NODE_PATH \
  && chown -R $BEATNAME $NODE_PATH

USER $BEATNAME

RUN npm i -g --loglevel verbose --engine-strict @elastic/synthetics@stack_release || sh -c 'tail -n +1 /usr/share/heartbeat/.npm/_logs/*' \
  && chmod ug+rwX -R $NODE_PATH
RUN chmod ug+rwX -R $NODE_PATH 
USER root

COPY --from=builder /usr/share/$BEATNAME /usr/share/$BEATNAME

USER 1000

ENV LIBBEAT_MONITORING_CGROUPS_HIERARCHY_OVERRIDE=/

WORKDIR $BEATHOME
ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/docker-entrypoint"]
CMD ["-environment", "container"]

#End of Dockerfile
