# © Copyright IBM Corporation 2017, 2026.
# LICENSE: Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)

#################### Dockerfile for Heartbeat 9.3.1 #############################
# Beats is the platform for single-purpose data shippers
#
# To build this image, from the directory containing this Dockerfile
# (assuming that the file is named Dockerfile):
# docker build -t <image_name> .
#
# To run, see "Run Heartbeat on Docker" guide available at https://www.elastic.co/guide/en/beats/heartbeat/current/running-on-docker.html
#################################################################################

# Base image
FROM ubuntu:22.04 AS builder

# The author
LABEL maintainer="LoZ Open Source Ecosystem (https://www.ibm.com/community/z/open-source/)"

ARG BEATS_VER=9.3.1

# Set environment variable
ENV BEATNAME=heartbeat
ENV BEATHOME=/usr/share/$BEATNAME
ENV SOURCE_DIR=/tmp/source
WORKDIR $SOURCE_DIR
ENV GOPATH=$SOURCE_DIR
ENV PATH=$PATH:/usr/local/go/bin/:$GOPATH/bin:/usr/local/bin:/opt/python3.11/bin
ENV GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=true
ENV PYTHON_EXE=python3.11
ENV TZ=America/Toronto

# Install dependencies
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    git \
    curl \
    make \
    wget \
    tar \
    gcc \
    g++ \
    libcap-dev \
    libpcap0.8-dev \
    openssl \
    libssh-dev \
    acl \
    rsync \
    patch \
    fdclone \
    libffi-dev \
    libsystemd-dev \
    libjpeg-dev \
    libbz2-dev \
    libdb-dev \
    libgdbm-dev \
    liblzma-dev \
    libncurses-dev \
    libreadline-dev \
    libsqlite3-dev \
    libssl-dev \
    tk-dev \
    uuid-dev \
    xz-utils \
    zlib1g-dev \
    iproute2 \
# Install Python 3.11.4
 && cd $SOURCE_DIR \
 && wget https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tgz \
 && tar -xzf Python-3.11.4.tgz \
 && cd Python-3.11.4 \
 && ./configure --prefix=/opt/python3.11 --enable-optimizations --with-lto \
 && make -j$(nproc) \
 && make install \
 && rm -rf Python* \
 && wget -O rustup-init.sh https://sh.rustup.rs \
 && bash rustup-init.sh -y \
 && export PATH=$PATH:$HOME/.cargo/bin \
# Install go and download beats source code
 && wget https://go.dev/dl/go1.24.11.linux-s390x.tar.gz \
 && chmod ugo+r go1.24.11.linux-s390x.tar.gz \
 && tar -C /usr/local -xzf go1.24.11.linux-s390x.tar.gz \
 && setfacl -dm u::rwx,g::r,o::r $GOPATH \
 && mkdir -p $GOPATH/src/github.com/elastic  \
 && cd $GOPATH/src/github.com/elastic  \
 && git clone -b v${BEATS_VER} https://github.com/elastic/beats.git  \
# Building heartbeat
 && cd $GOPATH/src/github.com/elastic/beats/${BEATNAME} \
 && make \
 && make update \
 && make fmt

# Setup directory layout
RUN mkdir -p $BEATHOME \
 && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/${BEATNAME} $BEATHOME \
 && cp $GOPATH/src/github.com/elastic/beats/LICENSE.txt $BEATHOME/LICENSE.txt \
 && cp $GOPATH/src/github.com/elastic/beats/NOTICE.txt  $BEATHOME/NOTICE.txt \
 && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/${BEATNAME}.reference.yml $BEATHOME \
 && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/fields.yml $BEATHOME \
 && cp -r $GOPATH/src/github.com/elastic/beats/${BEATNAME}/monitors.d $BEATHOME \
 && mkdir -p $BEATHOME/data $BEATHOME/logs \
 && chown -R root:root $BEATHOME \
 && find $BEATHOME -type d -exec chmod 0755 {} \; \
 && find $BEATHOME -type f -exec chmod 0644 {} \; \
 && chmod 0775 $BEATHOME/data $BEATHOME/logs \
 && chmod 0755 $BEATHOME/$BEATNAME

FROM docker.elastic.co/ubi9/ubi-minimal

LABEL maintainer="LoZ Open Source Ecosystem (https://www.ibm.com/community/z/open-source/)"

ENV ELASTIC_CONTAINER="true"
ENV BEATNAME=heartbeat
ENV BEATHOME=/usr/share/$BEATNAME
ENV PATH=$BEATHOME:$PATH
ENV GODEBUG=madvdontneed=1

RUN for iter in {1..10}; do \
        microdnf update -y && \
        microdnf -y install findutils shadow-utils ca-certificates \
        gawk libcap xz tar && \
        microdnf clean all && \
        exit_code=0 && break || exit_code=$? && echo "microdnf error: retry $iter in 10s" && sleep 10; \
    done; \
    (exit $exit_code)

RUN curl --retry 8 -S -L -O "https://github.com/krallin/tini/releases/download/v0.19.0/tini-s390x" \
 && mv tini-s390x /usr/bin/tini \
 && chmod +x /usr/bin/tini

COPY docker-entrypoint /usr/local/bin/docker-entrypoint
RUN chmod 755 /usr/local/bin/docker-entrypoint

COPY --from=builder /usr/share/$BEATNAME /usr/share/$BEATNAME
RUN readlink -f /usr/share/$BEATNAME/$BEATNAME | xargs setcap cap_net_raw+eip

RUN mkdir /licenses
COPY --from=builder /usr/share/$BEATNAME/LICENSE.txt /licenses
COPY --from=builder /usr/share/$BEATNAME/NOTICE.txt /licenses

RUN groupadd --gid 1000 $BEATNAME \
 && useradd -M --uid 1000 --gid 1000 --groups 0 --home $BEATHOME $BEATNAME

USER root

# Install the deps as needed by the exact version of playwright elastic synthetics uses
# We don't use npx playwright install-deps because that could pull a newer version
# Install additional fonts as well
RUN for iter in {1..10}; do \
    microdnf -y update && \
    microdnf -y install fontconfig freetype cairo glib2 gtk3 pango xorg-x11-fonts-misc xorg-x11-fonts-Type1 \
    at-spi2-atk atk at-spi2-core alsa-lib cups-libs dbus-libs libdrm mesa-libEGL mesa-libgbm nspr nss libX11 \
    libX11-xcb libxcb libXcomposite libXdamage libXext libXfixes libXrandr libxkbcommon libxshmfence glib2 \
    dbus-glib libicu mesa-libGL unzip \
    findutils shadow-utils ca-certificates gawk libcap xz tar -y && \
    mkdir -p /usr/share/fonts/google-noto && \
    curl -L -o NotoSansCJKjp.zip https://github.com/notofonts/noto-cjk/releases/download/Sans2.004/06_NotoSansCJKjp.zip && \
    unzip NotoSansCJKjp.zip -d /usr/share/fonts/google-noto && \
    rm -f NotoSansCJKjp.zip && \
    microdnf -y remove unzip && \
    curl -LO https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSans/NotoSans-Regular.ttf && \
    mv NotoSans-Regular.ttf /usr/share/fonts/google-noto && \
    curl -LO https://github.com/googlefonts/noto-emoji/raw/main/fonts/NotoColorEmoji.ttf && \
    mv NotoColorEmoji.ttf /usr/share/fonts/google-noto && \
    fc-cache -fv && \
    microdnf clean all && \
    exit_code=0 && break || exit_code=$? && echo "microdnf error: retry $iter in 10s" && sleep 10; \
done; \
(exit $exit_code)

ENV NODE_PATH=$BEATHOME/.node
RUN echo \
    $NODE_PATH \
    $BEATHOME/.config \
    $BEATHOME/.synthetics \
    $BEATHOME/.npm \
    $BEATHOME/.cache \
    | xargs -IDIR sh -c 'mkdir -m 0770 -p DIR && chown -R 1000 DIR'

# Setup synthetics env vars
ENV ELASTIC_SYNTHETICS_CAPABLE=true
ENV TZ=UTC
ENV NODE_VERSION=22.22.0
ENV PATH="$NODE_PATH/node/bin:$PATH"
# Install the latest version of @elastic/synthetics forcefully ignoring the previously
# cached node_modules, heartbeat then calls the global executable to run test suites
# Setup node
# Also try to add any deps that were missed earlier in terms of playwright reqs
# playwright install-deps is kept up to date with additional packages chromium needs
# beyond the base packages listed above
RUN cd /usr/share/heartbeat/.node \
  && NODE_DOWNLOAD_URL="https://nodejs.org/download/release/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-s390x.tar.xz" \
  && mkdir -p node \
  && curl ${NODE_DOWNLOAD_URL} | tar -xJ --strip 1 -C node \
  && chmod ug+rwX -R $NODE_PATH

# Install synthetics as a regular user, installing npm deps as root doesn't work
RUN chown -R 1000 $NODE_PATH
USER 1000
# If this fails dump the NPM logs
ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
RUN npm i -g --loglevel verbose --production --engine-strict @elastic/synthetics@stack_release || sh -c 'tail -n +1 /root/.npm/_logs/* && exit 1'
RUN chmod ug+rwX -R $NODE_PATH

ENV LIBBEAT_MONITORING_CGROUPS_HIERARCHY_OVERRIDE=/

WORKDIR $BEATHOME
ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/docker-entrypoint"]
CMD ["--environment", "container"]

#End of Dockerfile
